version: "3.9"

volumes:
  db-data:
  api:
  redis_data:

services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reminder
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reminder-api
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reminder
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data



