version: "3.9"

volumes:
  db-data:

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reminder
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./db-data:/var/lib/postgresql/data
       # copy the sql script to create tables
      - ./db/migrations/000001_create_todo.up.sql:/docker-entrypoint-initdb.d/000001_create_todo.up.sql

  reminder:
    build:
      context: .
      dockerfile: ./dockers/Dockerfile-reminder
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reminder
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: ./dockers/Dockerfile-worker
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reminder
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    ports:
      - "587:587"



