# Step 1: Modules caching
FROM golang:1.19-alpine as modules
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

# Step 2: Builder
FROM golang:1.19-alpine as builder
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /bin/app ./cmd/reminder

# Step 3: Final
FROM alpine:latest
RUN apk --no-cache add ca-certificates

EXPOSE 8000

# GOPATH for scratch images is /
COPY --from=builder /app/config.yaml /
COPY --from=builder /app/serviceAccountKey.json /
COPY --from=builder /bin/app /app
CMD ["/app"]