# Step 1: Modules caching
FROM golang:1.19-alpine as modules
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

# Step 2: Builder
FROM golang:1.19-alpine as builder
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /bin/app ./cmd/worker

# Step 3: Final
FROM alpine:latest
RUN wget https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz
RUN tar -xf migrate.linux-amd64.tar.gz
RUN mv migrate.linux-amd64 /usr/bin/migrate
RUN apk --no-cache add ca-certificates \
  && update-ca-certificates

# GOPATH for scratch images is /
COPY db/migrations/ /migrations/
COPY --from=builder /bin/app /app
CMD ["/app"]