basePath: /
definitions:
  domain.Todo:
    properties:
      completed:
        type: boolean
      created_at:
        type: string
      deadline_at:
        type: string
      deadline_notify:
        type: boolean
      description:
        type: string
      finished_at:
        type: string
      id:
        type: integer
      notificated:
        type: boolean
      notify_period:
        items:
          type: string
        type: array
      title:
        type: string
      user_id:
        type: string
    type: object
  domain.TodoInput:
    properties:
      created_at:
        type: string
      deadline_at:
        type: string
      deadline_notify:
        type: boolean
      description:
        type: string
      notify_period:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  domain.TodoResponse:
    properties:
      count:
        type: integer
      pageInfo:
        $ref: '#/definitions/pagination.PageInfo'
      todos:
        items:
          $ref: '#/definitions/domain.Todo'
        type: array
    type: object
  domain.TodoUpdateInput:
    properties:
      completed:
        type: boolean
      deadline_at:
        type: string
      deadline_notify:
        type: boolean
      description:
        type: string
      finished_at:
        type: string
      notificated:
        type: boolean
      notify_period:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  domain.TodoUpdateStatusInput:
    properties:
      completed:
        type: boolean
      finished_at:
        type: string
    type: object
  domain.UserConfigs:
    properties:
      ID:
        type: string
      created_at:
        type: string
      notification:
        type: boolean
      period:
        type: integer
      updated_at:
        type: string
    type: object
  pagination.Page:
    properties:
      cursor:
        description: Cursor describes the position in the database to start from
        type: integer
      filter:
        description: Filter describe filter params - by DeadlineAt or CreateAt
        type: string
      filterOption:
        description: FilterOption describe filterOption params - DESC or ASC
        type: string
      limit:
        description: Limit describes the number of records per request
        type: integer
    type: object
  pagination.PageInfo:
    properties:
      nextCursor:
        description: NextCursor describes the position of the next page
        type: integer
      page:
        allOf:
        - $ref: '#/definitions/pagination.Page'
        description: Page describes original request
    type: object
  utils.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Server for Reminder Application
  title: Reminder App API
  version: "1.0"
paths:
  /completed:
    get:
      consumes:
      - application/json
      description: GetCompletedReminds
      parameters:
      - description: limit
        in: query
        name: limit
        required: true
        type: string
      - description: cursor
        in: query
        name: cursor
        required: true
        type: string
      - description: filter
        in: query
        name: filter
        required: true
        type: string
      - description: filterOptions
        in: query
        name: filterOptions
        required: true
        type: string
      - description: start of time range
        in: query
        name: start
        required: true
        type: string
      - description: end of time range
        in: query
        name: end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.TodoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BasicAuth: []
      summary: return a list of completed reminds
      tags:
      - reminds
  /current:
    get:
      consumes:
      - application/json
      description: GetCurrentReminds
      parameters:
      - description: limit
        in: query
        name: limit
        required: true
        type: string
      - description: cursor
        in: query
        name: cursor
        required: true
        type: string
      - description: filter
        in: query
        name: filter
        required: true
        type: string
      - description: filterOption
        in: query
        name: filterOption
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.TodoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: return a list of current reminds
      tags:
      - reminds
  /remind:
    get:
      consumes:
      - application/json
      description: GetAllReminds
      parameters:
      - description: limit
        in: query
        name: limit
        required: true
        type: string
      - description: cursor
        in: query
        name: cursor
        required: true
        type: string
      - description: filter
        in: query
        name: filter
        required: true
        type: string
      - description: filterOptions
        in: query
        name: filterOptions
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.TodoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: return a list of all reminds
      tags:
      - reminds
    post:
      consumes:
      - application/json
      description: AddRemind
      parameters:
      - description: remind info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.TodoInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: create a new remind
      tags:
      - reminds
  /remind/{id}:
    get:
      consumes:
      - application/json
      description: GetRemindByID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: return a remind by id
      tags:
      - reminds
    put:
      consumes:
      - application/json
      description: UpdateRemind
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: update info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.TodoUpdateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: update remind with given fields
      tags:
      - reminds
  /remind{id}:
    delete:
      consumes:
      - application/json
      description: DeleteRemind
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: remind with id:1 successfully deleted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: delete remind
      tags:
      - reminds
  /status/{id}:
    put:
      consumes:
      - application/json
      description: UpdateCompleteStatus
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: update info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.TodoUpdateStatusInput'
      produces:
      - application/json
      responses:
        "200":
          description: remind status updated
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: update remind's field "completed"
      tags:
      - reminds
  /update-configs/{id}:
    put:
      consumes:
      - application/json
      description: UpdateUserConfig
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: update info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.UserConfigs'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: update user_config with given fields
      tags:
      - user_config
swagger: "2.0"
